version = 0.1

[default.deploy.parameters]
stack_name = "nba-prop-modeling"
resolve_s3 = true
s3_prefix = "nba-prop-modeling"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "BillingMode=\"PAY_PER_REQUEST\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
